import ExoticSpheres8And10
/-! Axiom audit. Run with `lake env lean audit/PrintAxioms.lean` after `lake build`.
Every theorem below must depend only on `propext`, `Classical.choice`, `Quot.sound`. -/

-- A2
#print axioms ExoticSpheres8And10.theta_attachSigma
#print axioms ExoticSpheres8And10.theta_attachSigmaHat
#print axioms ExoticSpheres8And10.attachSigmaHat_attachSigma
#print axioms ExoticSpheres8And10.attachSigma_attachSigmaHat
#print axioms ExoticSpheres8And10.attachSigmaEquiv
#print axioms ExoticSpheres8And10.attaching_boundary
#print axioms ExoticSpheres8And10.isConjEquivariant_conjAct
-- A7
#print axioms ExoticSpheres8And10.sinh_profile_bound
#print axioms ExoticSpheres8And10.sinh_profile_min_attained
-- A8
#print axioms ExoticSpheres8And10.boundary_eigenvalue_bound
#print axioms ExoticSpheres8And10.boundary_norm_bound
-- A9
#print axioms ExoticSpheres8And10.ker_eq_order3
#print axioms ExoticSpheres8And10.eq_zmod6Order3_of_card
#print axioms ExoticSpheres8And10.nat_card_ker
#print axioms ExoticSpheres8And10.castHom_ne_zero
#print axioms ExoticSpheres8And10.neg_generates_zmod3
#print axioms ExoticSpheres8And10.zmod3_generators
#print axioms ExoticSpheres8And10.zmod2_unique_nonzero
-- A1
#print axioms ExoticSpheres8And10.qcross_eq_crossProduct
#print axioms ExoticSpheres8And10.qdot_eq_inner
#print axioms ExoticSpheres8And10.commutator_eq_two_qcross
#print axioms ExoticSpheres8And10.norm_qcross_sq
#print axioms ExoticSpheres8And10.norm_qcross_le
#print axioms ExoticSpheres8And10.actionField_bound_dim8
#print axioms ExoticSpheres8And10.actionField_refined_dim8
#print axioms ExoticSpheres8And10.actionField_eq_dim8
#print axioms ExoticSpheres8And10.actionField_bound_dim10
#print axioms ExoticSpheres8And10.actionField_eq_dim10
-- A5
#print axioms ExoticSpheres8And10.norm_tmul_sub_tmul_sq
#print axioms ExoticSpheres8And10.wedgeSq_eq_half_norm_sq
#print axioms ExoticSpheres8And10.tensorSq_shear
#print axioms ExoticSpheres8And10.wedgeSq_shear
#print axioms ExoticSpheres8And10.tensorSq_wedgeSq_of_dependent
#print axioms ExoticSpheres8And10.area_ineq_a
#print axioms ExoticSpheres8And10.area_ineq_b
#print axioms ExoticSpheres8And10.area_ineqs_graph
-- A6
#print axioms ExoticSpheres8And10.criterion_scalar
#print axioms ExoticSpheres8And10.base_areas_pos_of_independent
#print axioms ExoticSpheres8And10.northNumerator_pos
-- A7(b-d)
#print axioms ExoticSpheres8And10.angular_step
#print axioms ExoticSpheres8And10.angular_chain
#print axioms ExoticSpheres8And10.radial_chain
#print axioms ExoticSpheres8And10.d_over_r_cubed_bound
-- A3
#print axioms ExoticSpheres8And10.det_id_sub_comp_comm
#print axioms ExoticSpheres8And10.conj_imEmb
#print axioms ExoticSpheres8And10.det_adMatrix
#print axioms ExoticSpheres8And10.det_toLin'_adMatrix
#print axioms ExoticSpheres8And10.dtheta_K
#print axioms ExoticSpheres8And10.beta_K
#print axioms ExoticSpheres8And10.det_id_sub_K_beta
#print axioms ExoticSpheres8And10.conj_orbit_hasDerivAt
-- A4
#print axioms ExoticSpheres8And10.gauge_potentials
#print axioms ExoticSpheres8And10.gauge_compatible
#print axioms ExoticSpheres8And10.dinv_of_leibniz
#print axioms ExoticSpheres8And10.hasDerivAt_quat_inv
#print axioms ExoticSpheres8And10.star_invariance_form
#print axioms ExoticSpheres8And10.star_invariance_mc
-- B1
#print axioms ExoticSpheres8And10.phiHom
#print axioms ExoticSpheres8And10.phiHom_spec
#print axioms ExoticSpheres8And10.phiHom_injective
#print axioms ExoticSpheres8And10.model_point
#print axioms ExoticSpheres8And10.exists_model_point
#print axioms ExoticSpheres8And10.injContEndoInner_Z2
-- B2
#print axioms ExoticSpheres8And10.theta_equivariant
-- B3
#print axioms ExoticSpheres8And10.lifts_differ_by_constant
#print axioms ExoticSpheres8And10.theta_const_along
#print axioms ExoticSpheres8And10.trivialLifts
-- D1
#print axioms ExoticSpheres8And10.hermite_endpoint_jets
#print axioms ExoticSpheres8And10.hasDerivAt_hermite
#print axioms ExoticSpheres8And10.hasDerivAt_hermite1
#print axioms ExoticSpheres8And10.hermite_estimate
#print axioms ExoticSpheres8And10.hermite1_estimate
#print axioms ExoticSpheres8And10.hermite2_estimate
#print axioms ExoticSpheres8And10.det_convex_comb
#print axioms ExoticSpheres8And10.det_pos_of_posDef2
#print axioms ExoticSpheres8And10.det_neg_fin_two
#print axioms ExoticSpheres8And10.tangent_bound
#print axioms ExoticSpheres8And10.tangent_reserve
#print axioms ExoticSpheres8And10.radial_reserve
#print axioms ExoticSpheres8And10.pointwise_of_opNorm
#print axioms ExoticSpheres8And10.rm_reparam
#print axioms ExoticSpheres8And10.gram_reparam
#print axioms ExoticSpheres8And10.all_planes_core
#print axioms ExoticSpheres8And10.all_planes
-- D2(a)
#print axioms ExoticSpheres8And10.sharp_to_master
#print axioms ExoticSpheres8And10.young
#print axioms ExoticSpheres8And10.master_to_reserve
#print axioms ExoticSpheres8And10.southlowerbound
#print axioms ExoticSpheres8And10.cS_pos
#print axioms ExoticSpheres8And10.rsq_bounds
#print axioms ExoticSpheres8And10.fibreRadius_derivs
#print axioms ExoticSpheres8And10.theta_bound
#print axioms ExoticSpheres8And10.lambdaMin_bound
-- D2(b)
#print axioms ExoticSpheres8And10.Prop31Algebra.brk_eq_two_cross
#print axioms ExoticSpheres8And10.Prop31Algebra.brk_sq
#print axioms ExoticSpheres8And10.Prop31Algebra.sum_wedge_sq
#print axioms ExoticSpheres8And10.Prop31Algebra.plucker
#print axioms ExoticSpheres8And10.Prop31Algebra.expand
#print axioms ExoticSpheres8And10.Prop31Algebra.BB_eq
#print axioms ExoticSpheres8And10.Prop31Algebra.Npart
#print axioms ExoticSpheres8And10.Prop31Algebra.Tpart
#print axioms ExoticSpheres8And10.Prop31Algebra.ΩXY_sq_le
#print axioms ExoticSpheres8And10.Prop31Algebra.cst_beta
#print axioms ExoticSpheres8And10.Prop31Algebra.bracket_BB
#print axioms ExoticSpheres8And10.Prop31Algebra.bracket_HHVV
#print axioms ExoticSpheres8And10.Prop31Algebra.Qpart
#print axioms ExoticSpheres8And10.Prop31Algebra.oneV_eq
#print axioms ExoticSpheres8And10.Prop31Algebra.oneV_bound
#print axioms ExoticSpheres8And10.Prop31Algebra.threeV_eq
#print axioms ExoticSpheres8And10.Prop31Algebra.threeV_bound
#print axioms ExoticSpheres8And10.Prop31Algebra.HHVV_eq
#print axioms ExoticSpheres8And10.Prop31Algebra.delta_sq
#print axioms ExoticSpheres8And10.Prop31Algebra.sharp_master
#print axioms ExoticSpheres8And10.Prop31Algebra.model_sharp_master
#print axioms ExoticSpheres8And10.Prop31Algebra.totalGram_eq
#print axioms ExoticSpheres8And10.Prop31Algebra.prop31_pointwise
-- Chains
#print axioms ExoticSpheres8And10.opNorm_le_two_of_sq
#print axioms ExoticSpheres8And10.norm_graphT_le
#print axioms ExoticSpheres8And10.inner_self_dtheta_eq_zero
#print axioms ExoticSpheres8And10.re_dtheta_mul_inv
#print axioms ExoticSpheres8And10.imEmb_betaCoord
#print axioms ExoticSpheres8And10.det_id_sub_K_beta_of_equivariance
#print axioms ExoticSpheres8And10.north_numerator_pos_of_profile
-- A1 derivative
#print axioms ExoticSpheres8And10.hasDerivAt_conj_orbit
#print axioms ExoticSpheres8And10.orbit8_velocity
#print axioms ExoticSpheres8And10.orbit10_velocity
#print axioms ExoticSpheres8And10.exp_curve
#print axioms ExoticSpheres8And10.K8_eq
#print axioms ExoticSpheres8And10.K10_eq
#print axioms ExoticSpheres8And10.lemK_rho8
#print axioms ExoticSpheres8And10.lemK_rho10
-- A8 compat
#print axioms ExoticSpheres8And10.shape_sum
#print axioms ExoticSpheres8And10.lift_ne_zero
#print axioms ExoticSpheres8And10.adjoint_graphT_comp
#print axioms ExoticSpheres8And10.eigen_KKstar_mem
#print axioms ExoticSpheres8And10.shape_relative_eigen
#print axioms ExoticSpheres8And10.compat_lower_bound
-- A3 Dsigma
#print axioms ExoticSpheres8And10.dsigma8
#print axioms ExoticSpheres8And10.dsigma10
#print axioms ExoticSpheres8And10.det_lmulMatrix
#print axioms ExoticSpheres8And10.det_rmulMatrix
#print axioms ExoticSpheres8And10.det_mulLeft
#print axioms ExoticSpheres8And10.det_mulRight
#print axioms ExoticSpheres8And10.det_adLin
#print axioms ExoticSpheres8And10.det_rho8
#print axioms ExoticSpheres8And10.det_rho10
#print axioms ExoticSpheres8And10.rho8_self
#print axioms ExoticSpheres8And10.rho10_self
#print axioms ExoticSpheres8And10.det_Dsigma8_ambient
-- B1 discharged
#print axioms ExoticSpheres8And10.circle_char
#print axioms ExoticSpheres8And10.circle_endo
#print axioms ExoticSpheres8And10.frame_rotation
#print axioms ExoticSpheres8And10.centralizer_pure
#print axioms ExoticSpheres8And10.unit_decomp
#print axioms ExoticSpheres8And10.phi_circle
#print axioms ExoticSpheres8And10.phi_re
#print axioms ExoticSpheres8And10.phi_qdot
#print axioms ExoticSpheres8And10.injContEndoInner_S3
#print axioms ExoticSpheres8And10.exists_model_point_S3
-- B1 continuity, A8 cometric, A3/A2 sphere
#print axioms ExoticSpheres8And10.phiHom_continuous
#print axioms ExoticSpheres8And10.exists_model_point_S3_top
#print axioms ExoticSpheres8And10.L_adjoint
#print axioms ExoticSpheres8And10.LLstar_eq
#print axioms ExoticSpheres8And10.cometric_lift
#print axioms ExoticSpheres8And10.rho8_dot
#print axioms ExoticSpheres8And10.sigma8_norm
#print axioms ExoticSpheres8And10.contDiffAt_sigma8
#print axioms ExoticSpheres8And10.contDiffAt_sigmaHat8
#print axioms ExoticSpheres8And10.K8_dot_self
#print axioms ExoticSpheres8And10.dtheta_radial_zero
#print axioms ExoticSpheres8And10.Dsigma8_normal
#print axioms ExoticSpheres8And10.Dsigma8_tangent
-- A7 existence
#print axioms ExoticSpheres8And10.hasDerivAt_Fprof
#print axioms ExoticSpheres8And10.hasDerivAt_Fprof'
#print axioms ExoticSpheres8And10.Fprof_le
#print axioms ExoticSpheres8And10.Fprof_G
#print axioms ExoticSpheres8And10.exists_Ceta
#print axioms ExoticSpheres8And10.deriv_etaCut_support
#print axioms ExoticSpheres8And10.hasDerivAt_rprof
#print axioms ExoticSpheres8And10.hasDerivAt_rprof'
#print axioms ExoticSpheres8And10.rprof_bounds
#print axioms ExoticSpheres8And10.rprof_end
#print axioms ExoticSpheres8And10.northern_filling_pos
#print axioms ExoticSpheres8And10.northern_filling_hyps_satisfiable

-- B3 transport (parallel transport on the trivial S³-bundle)
#print axioms ExoticSpheres8And10.norm_sat_le
#print axioms ExoticSpheres8And10.lipschitz_sat
#print axioms ExoticSpheres8And10.exists_transport
#print axioms ExoticSpheres8And10.transport_unique
#print axioms ExoticSpheres8And10.transportLifts
#print axioms ExoticSpheres8And10.transport_theta_const
#print axioms ExoticSpheres8And10.transport_theta_model

-- B3 gauge covariance
#print axioms ExoticSpheres8And10.star_deriv_mul_add
#print axioms ExoticSpheres8And10.gauge_ode
#print axioms ExoticSpheres8And10.gauge_pure
#print axioms ExoticSpheres8And10.gauge_isLift
#print axioms ExoticSpheres8And10.gauge_model

-- A2 sigma, sigma-hat as smooth maps of the manifold S^7
#print axioms ExoticSpheres8And10.fact_finrank_V8
#print axioms ExoticSpheres8And10.norm_rho8V
#print axioms ExoticSpheres8And10.contMDiff_rho8_sphere
#print axioms ExoticSpheres8And10.contMDiff_sigma8_sphere
#print axioms ExoticSpheres8And10.contMDiff_sigmaHat8_sphere
#print axioms ExoticSpheres8And10.sigma8_sphere_model

-- A6 division by the area
#print axioms ExoticSpheres8And10.area_pos
#print axioms ExoticSpheres8And10.sectional_pos_iff
#print axioms ExoticSpheres8And10.area_pos_model

-- A1 maximisers are not free
#print axioms ExoticSpheres8And10.eq_case_dim8
#print axioms ExoticSpheres8And10.maximizer_not_free_dim8
#print axioms ExoticSpheres8And10.eq_case_dim10
#print axioms ExoticSpheres8And10.maximizer_not_free_dim10

-- A2 sigma is a diffeomorphism of S^7 under eq:equiv
#print axioms ExoticSpheres8And10.sigmaHat_sigma
#print axioms ExoticSpheres8And10.sigma_sigmaHat
#print axioms ExoticSpheres8And10.sigmaDiffeo
#print axioms ExoticSpheres8And10.isEquivariant8_one

-- A7 at the centre
#print axioms ExoticSpheres8And10.G_neg
#print axioms ExoticSpheres8And10.Fprof_neg
#print axioms ExoticSpheres8And10.Fprof_contDiff
#print axioms ExoticSpheres8And10.Fprof_deriv_zero
#print axioms ExoticSpheres8And10.Fprof_second_zero
#print axioms ExoticSpheres8And10.Fprof_third_zero
#print axioms ExoticSpheres8And10.rprof_const_near_zero
#print axioms ExoticSpheres8And10.radial_curv_tendsto
#print axioms ExoticSpheres8And10.tangential_curv_tendsto

-- Glue (infrastructure: gluing two copies of a manifold)
#print axioms ExoticSpheres8And10.isManifold_glued
#print axioms ExoticSpheres8And10.contMDiff_ι₁
#print axioms ExoticSpheres8And10.contMDiff_ι₂
#print axioms ExoticSpheres8And10.contMDiff_of_comp_ι
#print axioms ExoticSpheres8And10.contMDiff_prod_glued
#print axioms ExoticSpheres8And10.contMDiff_glueLift
#print axioms ExoticSpheres8And10.t2Space_glued
#print axioms ExoticSpheres8And10.isOpenEmbedding_ι₁

-- S2 polar coordinates
#print axioms ExoticSpheres8And10.polar_decomp
#print axioms ExoticSpheres8And10.polar_unique
#print axioms ExoticSpheres8And10.polarT_map
#print axioms ExoticSpheres8And10.polarX_map
#print axioms ExoticSpheres8And10.capHomeo

-- S2 polar bundle
#print axioms ExoticSpheres8And10.isManifold_polarBundle
#print axioms ExoticSpheres8And10.PolarData.κP_starM
#print axioms ExoticSpheres8And10.PolarData.contMDiff_star
#print axioms ExoticSpheres8And10.PolarData.contMDiff_ract
#print axioms ExoticSpheres8And10.PolarData.contMDiff_proj
#print axioms ExoticSpheres8And10.PolarData.star_free
#print axioms ExoticSpheres8And10.PolarData.star_ract
#print axioms ExoticSpheres8And10.PolarData.proj_star
#print axioms ExoticSpheres8And10.PolarData.ract_free
#print axioms ExoticSpheres8And10.PolarData.ract_transitive

-- S2 quotient manifold
#print axioms ExoticSpheres8And10.isManifold_quotSpace
#print axioms ExoticSpheres8And10.PolarData.κS_Ψ
#print axioms ExoticSpheres8And10.PolarData.orbitMap_star
#print axioms ExoticSpheres8And10.PolarData.orbitMap_eq_iff
#print axioms ExoticSpheres8And10.PolarData.orbitMap_surjective
#print axioms ExoticSpheres8And10.PolarData.contMDiff_orbitMap
#print axioms ExoticSpheres8And10.PolarData.contMDiff_iff_comp_orbitMap

-- S2 lem:attaching
#print axioms ExoticSpheres8And10.PolarData.t2_polarBundle
#print axioms ExoticSpheres8And10.PolarData.t2_quotSpace
#print axioms ExoticSpheres8And10.PolarData.orbitSpaceHomeo
#print axioms ExoticSpheres8And10.PolarData.slice_unique
#print axioms ExoticSpheres8And10.PolarData.DNHomeo
#print axioms ExoticSpheres8And10.PolarData.DSHomeo
#print axioms ExoticSpheres8And10.PolarData.sigmaDiffeoV
#print axioms ExoticSpheres8And10.PolarData.markings
#print axioms ExoticSpheres8And10.PolarData.polarT_κS
#print axioms ExoticSpheres8And10.PolarData.polarX_κS
#print axioms ExoticSpheres8And10.PolarData.diskGluingHomeo
#print axioms ExoticSpheres8And10.PolarData.orbitSpaceDiskGluing

-- S2 summary and model
#print axioms ExoticSpheres8And10.bracket_orthonormal
#print axioms ExoticSpheres8And10.polarBundle_isStarBundle
#print axioms ExoticSpheres8And10.trivialPolarData

-- S3: prop:polar
#print axioms ExoticSpheres8And10.contDiff_intervalIntegral_param_infty
#print axioms ExoticSpheres8And10.contDiff_integral_param_infty
#print axioms ExoticSpheres8And10.integral_haarS3_mul_left
#print axioms ExoticSpheres8And10.LinCoeff.contDiff_T
#print axioms ExoticSpheres8And10.StarBundle.exists_model_point
#print axioms ExoticSpheres8And10.StarBundle.A_compat
#print axioms ExoticSpheres8And10.StarBundle.exists_lift
#print axioms ExoticSpheres8And10.StarBundle.lift_unique
#print axioms ExoticSpheres8And10.StarBundle.contMDiff_rayEnd
#print axioms ExoticSpheres8And10.StarBundle.hq_mul
#print axioms ExoticSpheres8And10.StarBundle.mu_mul
#print axioms ExoticSpheres8And10.StarBundle.contDiff_Abar
#print axioms ExoticSpheres8And10.StarBundle.Abar_re
#print axioms ExoticSpheres8And10.StarBundle.Abar_inv
#print axioms ExoticSpheres8And10.StarBundle.T_equiv
#print axioms ExoticSpheres8And10.StarBundle.sN_equiv
#print axioms ExoticSpheres8And10.StarBundle.equivSections
#print axioms ExoticSpheres8And10.EquivSections.normalFormDiffeo
#print axioms ExoticSpheres8And10.EquivSections.starQuotientHomeo
#print axioms ExoticSpheres8And10.StarBundle.prop_polar
#print axioms ExoticSpheres8And10.trivBundle
#print axioms ExoticSpheres8And10.prop_polar_trivBundle
#print axioms ExoticSpheres8And10.StarBundle.contMDiff_starQuotMap
#print axioms ExoticSpheres8And10.StarBundle.starQuotMap_surjective
#print axioms ExoticSpheres8And10.StarBundle.starQuotMap_eq_iff
#print axioms ExoticSpheres8And10.StarBundle.contMDiff_iff_comp_starQuotMap

-- §4
#print axioms ExoticSpheres8And10.starHorizontal_iff
#print axioms ExoticSpheres8And10.starGram_ge
#print axioms ExoticSpheres8And10.starVector_injective
#print axioms ExoticSpheres8And10.maurerCartan
#print axioms ExoticSpheres8And10.curvature_chi
#print axioms ExoticSpheres8And10.height_geodesic
#print axioms ExoticSpheres8And10.negHess_phi_ge
#print axioms ExoticSpheres8And10.bdata
#print axioms ExoticSpheres8And10.rS_reflect
#print axioms ExoticSpheres8And10.eventually_north_params
#print axioms ExoticSpheres8And10.hly_parameter_choice
#print axioms ExoticSpheres8And10.muN_eq

-- S5
#print axioms ExoticSpheres8And10.rhoHom
#print axioms ExoticSpheres8And10.rhoHom_smooth
#print axioms ExoticSpheres8And10.rep8
#print axioms ExoticSpheres8And10.rep10
#print axioms ExoticSpheres8And10.hasDerivAt_actionField
#print axioms ExoticSpheres8And10.lem_K
#print axioms ExoticSpheres8And10.prodBundle
#print axioms ExoticSpheres8And10.polar_and_K8
#print axioms ExoticSpheres8And10.polar_and_K10

-- S4: O'Neill (vendored `RiemannianGeometry` + ExoticSpheres8And10)
#print axioms RiemannianGeometry.pos_sectionalCurvatureAt_of_pos_of_mem_horizontalSpace
#print axioms RiemannianGeometry.leviCivita_spec
#print axioms RiemannianGeometry.eq_leviCivita
#print axioms ExoticSpheres8And10.isSubmersionAtPoint_of_section
#print axioms ExoticSpheres8And10.pos_sectionalCurvatureAt_base
#print axioms ExoticSpheres8And10.PolarData.orbitMap_isSubmersion
#print axioms ExoticSpheres8And10.PolarData.quotSpace_pos_sectionalCurvature

-- S4: coordinates, doubly warped curvature, northern positivity
#print axioms ExoticSpheres8And10.leviCivita_cmet
#print axioms ExoticSpheres8And10.riemannTensorAt_cmet
#print axioms ExoticSpheres8And10.wG_wΓ
#print axioms ExoticSpheres8And10.fderiv_wΓ
#print axioms ExoticSpheres8And10.riemannTensorAt_wG
#print axioms ExoticSpheres8And10.riemannTensorAt_wG_orthonormal
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_wG_pos_of_num
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_wG_pos
#print axioms ExoticSpheres8And10.HR_ΓR
#print axioms ExoticSpheres8And10.fibreRm_round
#print axioms ExoticSpheres8And10.deriv2_jetFun_self
#print axioms ExoticSpheres8And10.northern_sectionalCurvature_pos
#print axioms ExoticSpheres8And10.northern_sectionalCurvature_hyps_satisfiable

-- S4 north: local positivity, naturality, entire functions, pullbacks, model metric, quotient
#print axioms ExoticSpheres8And10.blend_eq
#print axioms ExoticSpheres8And10.blend_eventuallyEq
#print axioms ExoticSpheres8And10.blend_pos
#print axioms ExoticSpheres8And10.contDiff_blend
#print axioms ExoticSpheres8And10.deriv_blend
#print axioms ExoticSpheres8And10.deriv2_blend
#print axioms ExoticSpheres8And10.blend_self
#print axioms ExoticSpheres8And10.contDiff_rprof
#print axioms ExoticSpheres8And10.rprof_ge_of_le
#print axioms ExoticSpheres8And10.riemannTensorAt_wG_conformal
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_wG_pos_conformal
#print axioms ExoticSpheres8And10.northern_sectionalCurvature_pos_all
#print axioms ExoticSpheres8And10.two_le_infty'
#print axioms ExoticSpheres8And10.minSmoothness_two_le_infty
#print axioms ExoticSpheres8And10.mfderiv_mpullback
#print axioms ExoticSpheres8And10.mpullback_mfderiv
#print axioms ExoticSpheres8And10.pairing_mpullback
#print axioms ExoticSpheres8And10.koszulRHS_mpullback
#print axioms ExoticSpheres8And10.mfderiv_leviCivita_mpullback
#print axioms ExoticSpheres8And10.leviCivita_mpullback_eq
#print axioms ExoticSpheres8And10.mfderiv_curvature_mpullback
#print axioms ExoticSpheres8And10.riemannTensorAt_pullback
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_pullback
#print axioms ExoticSpheres8And10.ratio_tendsto_zero
#print axioms ExoticSpheres8And10.cCos_ratio
#print axioms ExoticSpheres8And10.cSinc_ratio
#print axioms ExoticSpheres8And10.radius_cCos
#print axioms ExoticSpheres8And10.radius_cSinc
#print axioms ExoticSpheres8And10.contDiff_sum_of_radius_top
#print axioms ExoticSpheres8And10.contDiff_cosSq
#print axioms ExoticSpheres8And10.contDiff_sincSq
#print axioms ExoticSpheres8And10.cosSq_eq_tsum
#print axioms ExoticSpheres8And10.sincSq_eq_tsum
#print axioms ExoticSpheres8And10.cosSq_sq
#print axioms ExoticSpheres8And10.sincSq_sq
#print axioms ExoticSpheres8And10.sincSq_zero
#print axioms ExoticSpheres8And10.cosSq_zero
#print axioms ExoticSpheres8And10.pullTerm_apply
#print axioms ExoticSpheres8And10.contMDiffAt_pullTerm_apply
#print axioms ExoticSpheres8And10.isContMDiffMetricSection_of_scalars
#print axioms ExoticSpheres8And10.contDiff_ψδ
#print axioms ExoticSpheres8And10.ψδ_nonneg
#print axioms ExoticSpheres8And10.mul_ψδ
#print axioms ExoticSpheres8And10.contMDiff_fY
#print axioms ExoticSpheres8And10.contMDiff_fQ
#print axioms ExoticSpheres8And10.contMDiff_fU
#print axioms ExoticSpheres8And10.northMetric_apply
#print axioms ExoticSpheres8And10.isContMDiffMetricSection_northMetric
#print axioms ExoticSpheres8And10.isSymm_northMetric
#print axioms ExoticSpheres8And10.mvfderiv_fY
#print axioms ExoticSpheres8And10.mvfderiv_fU_injective
#print axioms ExoticSpheres8And10.isPosDef_northMetric
#print axioms ExoticSpheres8And10.mvfderiv_comp'
#print axioms ExoticSpheres8And10.mvfderiv_clm_comp
#print axioms ExoticSpheres8And10.πN_starN
#print axioms ExoticSpheres8And10.contMDiff_starN
#print axioms ExoticSpheres8And10.contMDiff_πN
#print axioms ExoticSpheres8And10.inner_mul_left_unit
#print axioms ExoticSpheres8And10.northMetric_starN
#print axioms ExoticSpheres8And10.mfderiv_orbit
#print axioms ExoticSpheres8And10.mdifferentiableAt_orbit
#print axioms ExoticSpheres8And10.ρV_one_apply
#print axioms ExoticSpheres8And10.hasMFDerivAt_orbit
#print axioms ExoticSpheres8And10.inner_Y_KY
#print axioms ExoticSpheres8And10.dπN_apply
#print axioms ExoticSpheres8And10.mvfderiv_fQ
#print axioms ExoticSpheres8And10.mvfderiv_fU
#print axioms ExoticSpheres8And10.Gs_apply
#print axioms ExoticSpheres8And10.northMetric_slice
#print axioms ExoticSpheres8And10.Gs_symm
#print axioms ExoticSpheres8And10.Gs_pos
#print axioms ExoticSpheres8And10.contDiff_Gs_apply
#print axioms ExoticSpheres8And10.hz_apply
#print axioms ExoticSpheres8And10.forall_basis_eq_zero
#print axioms ExoticSpheres8And10.hz_eq_zero_iff
#print axioms ExoticSpheres8And10.ιv_apply
#print axioms ExoticSpheres8And10.dπl_apply
#print axioms ExoticSpheres8And10.Φs_injective
#print axioms ExoticSpheres8And10.coe_Φe
#print axioms ExoticSpheres8And10.isInvertible_Φs
#print axioms ExoticSpheres8And10.Φs_hlift
#print axioms ExoticSpheres8And10.dπl_hlift
#print axioms ExoticSpheres8And10.hlift_horizontal
#print axioms ExoticSpheres8And10.eq_hlift
#print axioms ExoticSpheres8And10.gB_symm
#print axioms ExoticSpheres8And10.gB_pos
#print axioms ExoticSpheres8And10.contDiff_Φs
#print axioms ExoticSpheres8And10.contDiff_hlift_apply
#print axioms ExoticSpheres8And10.contDiff_gB
#print axioms ExoticSpheres8And10.pos_sectionalCurvatureAt_base_of_mem
#print axioms ExoticSpheres8And10.dπN_eq
#print axioms ExoticSpheres8And10.πN_slice
#print axioms ExoticSpheres8And10.isSubmersionAtPoint_πN
#print axioms ExoticSpheres8And10.surjective_πN
#print axioms ExoticSpheres8And10.isRiemannianSubmersionAtPoint_πN_slice
#print axioms ExoticSpheres8And10.isRiemannianSubmersionAtPoint_πN
#print axioms ExoticSpheres8And10.isSymm_cmet_gB
#print axioms ExoticSpheres8And10.isPosDef_cmet_gB
#print axioms ExoticSpheres8And10.two_le_top_nat
#print axioms ExoticSpheres8And10.northQuot_sectionalCurvature_pos

-- S4 north: germ locality, charts, upstairs positivity, centre, assembly
#print axioms ExoticSpheres8And10.koszulRHS_congr_metric
#print axioms ExoticSpheres8And10.leviCivita_congr_metric
#print axioms ExoticSpheres8And10.curvature_congr_metric
#print axioms ExoticSpheres8And10.riemannTensorAt_congr_metric
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_congr_metric
#print axioms ExoticSpheres8And10.contDiff_ηs
#print axioms ExoticSpheres8And10.contDiff_lgs
#print axioms ExoticSpheres8And10.contDiff_reparam
#print axioms ExoticSpheres8And10.ηs_nonneg
#print axioms ExoticSpheres8And10.ηs_le_one
#print axioms ExoticSpheres8And10.ηs_zero
#print axioms ExoticSpheres8And10.ηs_one
#print axioms ExoticSpheres8And10.ηs_monotone
#print axioms ExoticSpheres8And10.lgs_pos
#print axioms ExoticSpheres8And10.lgs_lt
#print axioms ExoticSpheres8And10.hasDerivAt_lgs
#print axioms ExoticSpheres8And10.deriv_ηs_eq_zero
#print axioms ExoticSpheres8And10.hasDerivAt_reparam
#print axioms ExoticSpheres8And10.reparamDeriv_pos
#print axioms ExoticSpheres8And10.reparam_pos
#print axioms ExoticSpheres8And10.reparam_eq
#print axioms ExoticSpheres8And10.reparam_eventuallyEq
#print axioms ExoticSpheres8And10.dst_add
#print axioms ExoticSpheres8And10.dst_smul
#print axioms ExoticSpheres8And10.hasFDerivAt_stereo
#print axioms ExoticSpheres8And10.contDiff_stereo
#print axioms ExoticSpheres8And10.norm_stereo_sq
#print axioms ExoticSpheres8And10.norm_stereo
#print axioms ExoticSpheres8And10.inner_stereo_dst
#print axioms ExoticSpheres8And10.inner_dst_dst
#print axioms ExoticSpheres8And10.stereo_zero
#print axioms ExoticSpheres8And10.dst_zero
#print axioms ExoticSpheres8And10.ι3_apply
#print axioms ExoticSpheres8And10.norm_ι3
#print axioms ExoticSpheres8And10.inner_ι3
#print axioms ExoticSpheres8And10.inner_ι3_one
#print axioms ExoticSpheres8And10.norm_one_quat
#print axioms ExoticSpheres8And10.σ3_val
#print axioms ExoticSpheres8And10.contMDiff_σ3
#print axioms ExoticSpheres8And10.z30_eq
#print axioms ExoticSpheres8And10.σ3_z30
#print axioms ExoticSpheres8And10.mfderiv_σ3
#print axioms ExoticSpheres8And10.hasFDerivAt_val_σ3
#print axioms ExoticSpheres8And10.mvfderiv_vs
#print axioms ExoticSpheres8And10.deriv_reparam_eq_one
#print axioms ExoticSpheres8And10.deriv_reparam_pos
#print axioms ExoticSpheres8And10.inner_Hs_e
#print axioms ExoticSpheres8And10.Gh_apply
#print axioms ExoticSpheres8And10.contDiff_Fh
#print axioms ExoticSpheres8And10.contDiff_Gh
#print axioms ExoticSpheres8And10.isSymm_Gh
#print axioms ExoticSpheres8And10.Gh_pos
#print axioms ExoticSpheres8And10.isPosDef_Gh
#print axioms ExoticSpheres8And10.Gh_eventuallyEq
#print axioms ExoticSpheres8And10.contDiff_Φh_fst
#print axioms ExoticSpheres8And10.contMDiff_Φh
#print axioms ExoticSpheres8And10.fderiv_Φh_fst
#print axioms ExoticSpheres8And10.fderiv_Φh_snd
#print axioms ExoticSpheres8And10.hasDerivAt_Fh
#print axioms ExoticSpheres8And10.hpull_Φh
#print axioms ExoticSpheres8And10.mfderiv_Φh_injective
#print axioms ExoticSpheres8And10.finrank_Mc
#print axioms ExoticSpheres8And10.isInvertible_mfderiv_Φh
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_Φh
#print axioms ExoticSpheres8And10.mfderiv_Φh_apply
#print axioms ExoticSpheres8And10.Φh_p0
#print axioms ExoticSpheres8And10.psiR_zero
#print axioms ExoticSpheres8And10.psiR_z30
#print axioms ExoticSpheres8And10.mfderiv_Φh_p0
#print axioms ExoticSpheres8And10.KY_smul
#print axioms ExoticSpheres8And10.KY_mem
#print axioms ExoticSpheres8And10.Kh_coe
#print axioms ExoticSpheres8And10.norm_Kh_le
#print axioms ExoticSpheres8And10.mfderiv_Φh_wv
#print axioms ExoticSpheres8And10.north_up_pos
#print axioms ExoticSpheres8And10.Gw_apply
#print axioms ExoticSpheres8And10.contDiff_Gw
#print axioms ExoticSpheres8And10.isSymm_Gw
#print axioms ExoticSpheres8And10.Gw_pos
#print axioms ExoticSpheres8And10.isPosDef_Gw
#print axioms ExoticSpheres8And10.contMDiff_Φc
#print axioms ExoticSpheres8And10.hpull_Φc
#print axioms ExoticSpheres8And10.isInvertible_mfderiv_Φc
#print axioms ExoticSpheres8And10.fderiv_Gw_const_apply
#print axioms ExoticSpheres8And10.G0_Γ0
#print axioms ExoticSpheres8And10.contDiff_cb
#print axioms ExoticSpheres8And10.contDiffAt_Γ0
#print axioms ExoticSpheres8And10.cb_zero
#print axioms ExoticSpheres8And10.ψδ_zero
#print axioms ExoticSpheres8And10.fderiv_Γ0_centre
#print axioms ExoticSpheres8And10.contDiff2_G0
#print axioms ExoticSpheres8And10.riemannTensorAt_G0_centre
#print axioms ExoticSpheres8And10.KY_zero
#print axioms ExoticSpheres8And10.mfderiv_Φc_centre
#print axioms ExoticSpheres8And10.north_centre_pos
#print axioms ExoticSpheres8And10.contDiff_G
#print axioms ExoticSpheres8And10.G_nonneg
#print axioms ExoticSpheres8And10.rprof_eq_start
#print axioms ExoticSpheres8And10.rD_eventually_const
#print axioms ExoticSpheres8And10.contDiff_rD
#print axioms ExoticSpheres8And10.rD_invariant
#print axioms ExoticSpheres8And10.rD_ray
#print axioms ExoticSpheres8And10.rD_pos
#print axioms ExoticSpheres8And10.north_hup
#print axioms ExoticSpheres8And10.northern_quotient_pos
#print axioms ExoticSpheres8And10.northern_quotient_hyps_satisfiable
-- HLY model (§4, Prop 3.1 frame computation)
#print axioms ExoticSpheres8And10.riemannTensorAt_frame
#print axioms ExoticSpheres8And10.isContMDiffMetricSection_GH
#print axioms ExoticSpheres8And10.GH_Fr
#print axioms ExoticSpheres8And10.mlieBracket_Fr
#print axioms ExoticSpheres8And10.riemannTensorAt_Fr
#print axioms ExoticSpheres8And10.fderiv_Ωc_vert
#print axioms ExoticSpheres8And10.RmA_HVHV
#print axioms ExoticSpheres8And10.RmA_HHVV
#print axioms ExoticSpheres8And10.RmA_HVVV
#print axioms ExoticSpheres8And10.RmA_HHHV
#print axioms ExoticSpheres8And10.RmA_VVVV
#print axioms ExoticSpheres8And10.RmA_HHHH
#print axioms ExoticSpheres8And10.hly_blocks_hyps_satisfiable
-- HLY package (D2's interface, from `RiemannianGeometry`'s curvature)
#print axioms ExoticSpheres8And10.riemannTensorAt_vecF
#print axioms ExoticSpheres8And10.RmP_swap_left
#print axioms ExoticSpheres8And10.RmP_swap_right
#print axioms ExoticSpheres8And10.RmP_pair
#print axioms ExoticSpheres8And10.RmP_HVHV
#print axioms ExoticSpheres8And10.RmP_HHVV
#print axioms ExoticSpheres8And10.RmP_HVVV
#print axioms ExoticSpheres8And10.RmP_HHHV
#print axioms ExoticSpheres8And10.RmP_VVVV
#print axioms ExoticSpheres8And10.RmP_HHHH
#print axioms ExoticSpheres8And10.hly_prop31_centre
#print axioms ExoticSpheres8And10.hly_prop31_centre_satisfiable
-- HLY blocks and Prop 3.1 at every base point
#print axioms ExoticSpheres8And10.base_curv
#print axioms ExoticSpheres8And10.RmAy_HVHV
#print axioms ExoticSpheres8And10.RmAy_HHVV
#print axioms ExoticSpheres8And10.RmAy_HVVV
#print axioms ExoticSpheres8And10.RmAy_HHHV
#print axioms ExoticSpheres8And10.RmAy_VVVV
#print axioms ExoticSpheres8And10.RmAy_HHHH
#print axioms ExoticSpheres8And10.hly_prop31_at
#print axioms ExoticSpheres8And10.data_y_zero
-- the southern filling
#print axioms ExoticSpheres8And10.GH_vecF
#print axioms ExoticSpheres8And10.sec_pos_of_bound
#print axioms ExoticSpheres8And10.hly_sec_pos_at
#print axioms ExoticSpheres8And10.ϑf_rSy
#print axioms ExoticSpheres8And10.Ny_rSy
#print axioms ExoticSpheres8And10.Ny_rSy_ge
#print axioms ExoticSpheres8And10.rSy_sq_le
#print axioms ExoticSpheres8And10.isCompact_capS
#print axioms ExoticSpheres8And10.southern_cap_pos
#print axioms ExoticSpheres8And10.southern_cap_pos_hyps
-- the star quotient (generic) and the southern quotient
#print axioms ExoticSpheres8And10.SQ.eq_hlift
#print axioms ExoticSpheres8And10.SQ.contDiff_gB
#print axioms ExoticSpheres8And10.SQ.isRiemannianSubmersionAtPoint_all
#print axioms ExoticSpheres8And10.SQ.quot_sectionalCurvature_pos
#print axioms ExoticSpheres8And10.GH_slice
#print axioms ExoticSpheres8And10.GH_starN
#print axioms ExoticSpheres8And10.southern_quotient_pos
#print axioms ExoticSpheres8And10.southern_quotient_hyps_satisfiable
-- [GG]'s southern potential from the polar data
#print axioms ExoticSpheres8And10.PolarData.contMDiff_ρVs
#print axioms ExoticSpheres8And10.PolarData.contDiffAt_θh
#print axioms ExoticSpheres8And10.PolarData.θh_ρ
#print axioms ExoticSpheres8And10.PolarData.contDiff_AS
#print axioms ExoticSpheres8And10.PolarData.AS_im
#print axioms ExoticSpheres8And10.PolarData.AS_equiv
#print axioms ExoticSpheres8And10.southern_quotient_pos_D
-- second fundamental forms and the RW hypothesis (definitions + infrastructure)
#print axioms ExoticSpheres8And10.g_gradAt
#print axioms ExoticSpheres8And10.eq_gradAt
#print axioms ExoticSpheres8And10.G_leviCivita_cmet_self
#print axioms ExoticSpheres8And10.sff_cmet
#print axioms ExoticSpheres8And10.sff_pullback
#print axioms ExoticSpheres8And10.sff_comp_of_pos
#print axioms ExoticSpheres8And10.sff_neg
#print axioms ExoticSpheres8And10.sff_warp
#print axioms ExoticSpheres8And10.unitNormal_Gwarp
#print axioms ExoticSpheres8And10.sff_submersion
-- boundary analysis: warped sources, quotient sff, local naturality
#print axioms ExoticSpheres8And10.hpull_Φc_GW
#print axioms ExoticSpheres8And10.GW_starN
#print axioms ExoticSpheres8And10.contDiffAt_unitNormal_cmet
#print axioms ExoticSpheres8And10.sff_quot_GW
#print axioms ExoticSpheres8And10.mfderiv_leviCivita_mpullback_loc
#print axioms ExoticSpheres8And10.sff_pullback_loc
#print axioms ExoticSpheres8And10.PolarData.π_Λ
#print axioms ExoticSpheres8And10.PolarData.Λ_isometry
#print axioms ExoticSpheres8And10.PolarData.σh_τ
#print axioms ExoticSpheres8And10.PolarData.gB_τ
#print axioms ExoticSpheres8And10.hlift_match
#print axioms ExoticSpheres8And10.gB_match
-- boundary values: northern/southern base and fibre terms, model boundary theorems, gauge sff
#print axioms ExoticSpheres8And10.gB_eq_SQ
#print axioms ExoticSpheres8And10.baseN_eq
#print axioms ExoticSpheres8And10.fibreN
#print axioms ExoticSpheres8And10.PolarData.baseS_eq
#print axioms ExoticSpheres8And10.PolarData.baseS_factor_nonneg
#print axioms ExoticSpheres8And10.PolarData.fibreS
#print axioms ExoticSpheres8And10.PolarData.bdry_model_metric
#print axioms ExoticSpheres8And10.PolarData.bdry_model_sff
#print axioms ExoticSpheres8And10.PolarData.isInvertible_fderiv_τ
#print axioms ExoticSpheres8And10.PolarData.sff_τ
#print axioms ExoticSpheres8And10.PolarData.bdry_model_hyps_satisfiable
-- Stage E: charts of X = P_θ/S³⋆, transition, the Reiser–Wraith datum, thm:HLYgeneral
#print axioms ExoticSpheres8And10.mfderiv_opens_val
#print axioms ExoticSpheres8And10.isContMDiffMetricSection_pullMet
#print axioms ExoticSpheres8And10.isPosDef_pullMet
#print axioms ExoticSpheres8And10.stD
#print axioms ExoticSpheres8And10.inner_e_stD
#print axioms ExoticSpheres8And10.PolarData.ψ₁
#print axioms ExoticSpheres8And10.PolarData.ψ₂
#print axioms ExoticSpheres8And10.PolarData.fX_U₁
#print axioms ExoticSpheres8And10.PolarData.fX_U₂
#print axioms ExoticSpheres8And10.stereo_reflE
#print axioms ExoticSpheres8And10.PolarData.θS_of_dir
#print axioms ExoticSpheres8And10.PolarData.stD_κS
#print axioms ExoticSpheres8And10.PolarData.ψ₂X_eq
#print axioms ExoticSpheres8And10.PolarData.mfderiv_ψ₂_eq
#print axioms ExoticSpheres8And10.PolarData.subN
#print axioms ExoticSpheres8And10.PolarData.subS
#print axioms ExoticSpheres8And10.PolarData.regular
#print axioms ExoticSpheres8And10.PolarData.inner_ψN_of_df
#print axioms ExoticSpheres8And10.PolarData.posN_aux
#print axioms ExoticSpheres8And10.PolarData.posS_aux
#print axioms ExoticSpheres8And10.PolarData.bdry_metric_aux
#print axioms ExoticSpheres8And10.PolarData.bdry_sff_aux
#print axioms ExoticSpheres8And10.PolarData.rwData
#print axioms ExoticSpheres8And10.PolarData.model_hbm
#print axioms ExoticSpheres8And10.PolarData.model_hbs
#print axioms ExoticSpheres8And10.PolarData.compactSpace_quotSpace
#print axioms ExoticSpheres8And10.isSouthCutoff_χD
#print axioms ExoticSpheres8And10.hly_general
-- Stage F: lem:K ⇒ hly_general hypothesis; Theorems A, B; Corollary C (bookkeeping)
#print axioms ExoticSpheres8And10.Dq_apply
#print axioms ExoticSpheres8And10.KY_eq_of_hasDerivAt
#print axioms ExoticSpheres8And10.norm_KY_le
#print axioms ExoticSpheres8And10.theoremA
#print axioms ExoticSpheres8And10.theoremB
-- Smooth bridge: E/S³_⋆ as a smooth manifold; positive curvature transported along diffeomorphisms
#print axioms ExoticSpheres8And10.isSymm_pullbackForm
#print axioms ExoticSpheres8And10.isPosDef_pullbackForm
#print axioms ExoticSpheres8And10.mpullback_symm_apply_self
#print axioms ExoticSpheres8And10.isContMDiffMetricSection_pullbackForm
#print axioms ExoticSpheres8And10.HasPosCurvMetric.of_diffeomorph
#print axioms ExoticSpheres8And10.StarBundle.isSmoothStarQuotient_starQuotMap
#print axioms ExoticSpheres8And10.StarBundle.IsSmoothStarQuotient.lift_comp
#print axioms ExoticSpheres8And10.StarBundle.IsSmoothStarQuotient.diffeomorph
#print axioms ExoticSpheres8And10.StarBundle.IsSmoothStarQuotient.diffeomorph_comp
#print axioms ExoticSpheres8And10.polarModelA
#print axioms ExoticSpheres8And10.polarModelB
#print axioms ExoticSpheres8And10.corollaryC_dim10
#print axioms ExoticSpheres8And10.corollaryC_dim8
#print axioms ExoticSpheres8And10.corollaryC_dim10_satisfiable
-- rem:general_bound (final preprint)
#print axioms ExoticSpheres8And10.inv_θ_equiv
#print axioms ExoticSpheres8And10.StarRep.polarOf
#print axioms ExoticSpheres8And10.sigmaV_eq_J
#print axioms ExoticSpheres8And10.polarOf_inv
#print axioms ExoticSpheres8And10.remark_general_bound
-- DHZ Prop 5.1; general K bound; remark from RW alone
#print axioms ExoticSpheres8And10.northern_filling_pos_L
#print axioms ExoticSpheres8And10.exists_rwData_L
#print axioms ExoticSpheres8And10.hly_general_L
#print axioms ExoticSpheres8And10.norm_KY_le_dρ
#print axioms ExoticSpheres8And10.exists_K_bound
#print axioms ExoticSpheres8And10.dhz_prop51
#print axioms ExoticSpheres8And10.dhzGluing_of_RW
#print axioms ExoticSpheres8And10.remark_general_bound_RW
-- G1: closed disks, lem:attaching (1), (3) smooth
#print axioms ExoticSpheres8And10.regDom_isManifold
#print axioms ExoticSpheres8And10.contMDiff_val_regDom
#print axioms ExoticSpheres8And10.isInvertible_mfderiv_val_regDom
#print axioms ExoticSpheres8And10.isBoundaryPoint_regDom_iff
#print axioms ExoticSpheres8And10.diskIsManifold
#print axioms ExoticSpheres8And10.isBoundaryPoint_disk_iff
#print axioms ExoticSpheres8And10.compactSpace_cdisk
#print axioms ExoticSpheres8And10.mul_muR
#print axioms ExoticSpheres8And10.muR_add_deriv_pos
#print axioms ExoticSpheres8And10.injective_fderiv_radialR
#print axioms ExoticSpheres8And10.stereoInv_radialR
#print axioms ExoticSpheres8And10.PolarData.contMDiff_jN
#print axioms ExoticSpheres8And10.PolarData.contMDiff_jS
#print axioms ExoticSpheres8And10.PolarData.isInvertible_mfderiv_jN
#print axioms ExoticSpheres8And10.PolarData.isInvertible_mfderiv_jS
#print axioms ExoticSpheres8And10.PolarData.isClosedEmbedding_jN
#print axioms ExoticSpheres8And10.PolarData.isClosedEmbedding_jS
#print axioms ExoticSpheres8And10.PolarData.range_jN
#print axioms ExoticSpheres8And10.PolarData.range_jS
#print axioms ExoticSpheres8And10.PolarData.isBoundaryPoint_iff_jN_mem_DS
#print axioms ExoticSpheres8And10.PolarData.isBoundaryPoint_iff_jS_mem_DN
#print axioms ExoticSpheres8And10.PolarData.range_jN_union_range_jS
#print axioms ExoticSpheres8And10.PolarData.jN_eq_jS_iff
#print axioms ExoticSpheres8And10.PolarData.lem_attaching_smooth
-- G1 caveats: radial diffeomorphism, product-collar gluing, X as a model
#print axioms ExoticSpheres8And10.injOn_radialR
#print axioms ExoticSpheres8And10.contDiffOn_radialPH_symm
#print axioms ExoticSpheres8And10.DiskGluingModel.glueDiffeo
#print axioms ExoticSpheres8And10.DiskGluingModel.shrink
#print axioms ExoticSpheres8And10.diskGluing_unique
#print axioms ExoticSpheres8And10.collarTau_boundary
#print axioms ExoticSpheres8And10.PolarData.κS_diskPt_tau
#print axioms ExoticSpheres8And10.PolarData.xModel
#print axioms ExoticSpheres8And10.PolarData.lem_attaching_1
#print axioms ExoticSpheres8And10.PolarData.lem_attaching_3
#print axioms ExoticSpheres8And10.PolarData.DN_eq_ψN_image
-- Corollary C: scalar curvature, round sphere, geometric SEC/PSC
#print axioms ExoticSpheres8And10.exists_orthonormalFrame
#print axioms ExoticSpheres8And10.scalarCurvatureAt_pos
#print axioms ExoticSpheres8And10.HasPosCurvMetric.hasPosScalMetric
#print axioms ExoticSpheres8And10.sectionalCurvatureAt_HR
#print axioms ExoticSpheres8And10.hasPosCurvMetric_sphere
#print axioms ExoticSpheres8And10.hasPosScalMetric_sphere
#print axioms ExoticSpheres8And10.SECc_PSCc
#print axioms ExoticSpheres8And10.SECc_zero
#print axioms ExoticSpheres8And10.SECc_of_theoremA
#print axioms ExoticSpheres8And10.SECc_of_theoremB
#print axioms ExoticSpheres8And10.corollaryC_dim10_geom
#print axioms ExoticSpheres8And10.corollaryC_dim8_geom
#print axioms ExoticSpheres8And10.corollaryC_dim10_geom_satisfiable
-- eq:compat strict
#print axioms ExoticSpheres8And10.PolarData.gB_le_base
#print axioms ExoticSpheres8And10.PolarData.bdry_model_sff_cB
#print axioms ExoticSpheres8And10.PolarData.bdry_model_compat
-- fact:prop31 (HLY Prop. 3.1), global: principal S^3-bundles, base with boundary
#print axioms ExoticSpheres8And10.S3Connection.riemannTensorAt_Fr
#print axioms ExoticSpheres8And10.S3Connection.riemannTensorAt_vecFP
#print axioms ExoticSpheres8And10.S3Connection.prop31_at_P
#print axioms ExoticSpheres8And10.exists_orthonormal_frame_near
#print axioms ExoticSpheres8And10.riemannTensorAt_base_frame
#print axioms ExoticSpheres8And10.KB_ge_of_sec
#print axioms ExoticSpheres8And10.hessF_frame_sum
#print axioms ExoticSpheres8And10.NB_quad_ge
#print axioms ExoticSpheres8And10.gradSq_frame_indep
#print axioms ExoticSpheres8And10.eps_budget
#print axioms ExoticSpheres8And10.hly_prop31_global
#print axioms ExoticSpheres8And10.flatConn
#print axioms ExoticSpheres8And10.hessF_one_dim
#print axioms ExoticSpheres8And10.hessF_model
#print axioms ExoticSpheres8And10.hly_prop31_global_model
-- fact:prop31: intrinsic hypotheses (frame/gauge invariance), Hessian tensor, dim-2 model
#print axioms ExoticSpheres8And10.S3Connection.hlift_gauge
#print axioms ExoticSpheres8And10.S3Connection.tΩ_eq_conn_bracket
#print axioms ExoticSpheres8And10.S3Connection.tΩ_gauge
#print axioms ExoticSpheres8And10.S3Connection.tΩ_frame
#print axioms ExoticSpheres8And10.S3Connection.OmSq_frame
#print axioms ExoticSpheres8And10.S3Connection.ΓB_frame
#print axioms ExoticSpheres8And10.S3Connection.DΩP_frame
#print axioms ExoticSpheres8And10.S3Connection.DΩP_gauge
#print axioms ExoticSpheres8And10.S3Connection.DΩsq_frame
#print axioms ExoticSpheres8And10.DΩ_matrix
#print axioms ExoticSpheres8And10.hessF_expand_right
#print axioms ExoticSpheres8And10.hessAt_eq
#print axioms ExoticSpheres8And10.S3Connection.curvNormSq_eq
#print axioms ExoticSpheres8And10.S3Connection.dcurvNormSq_eq
#print axioms ExoticSpheres8And10.S3Connection.continuous_curvNormSq
#print axioms ExoticSpheres8And10.S3Connection.continuous_dcurvNormSq
#print axioms ExoticSpheres8And10.S3Connection.exists_curv_bounds
#print axioms ExoticSpheres8And10.hly_prop31_global_intrinsic
#print axioms ExoticSpheres8And10.hly_prop31_intrinsic_interval
#print axioms ExoticSpheres8And10.potConn
#print axioms ExoticSpheres8And10.curvF_potConn
#print axioms ExoticSpheres8And10.hessF_mpullback
#print axioms ExoticSpheres8And10.hess_hRA
#print axioms ExoticSpheres8And10.sec_gD
#print axioms ExoticSpheres8And10.hessAt_φD
#print axioms ExoticSpheres8And10.curvNormSq_disk_pos
#print axioms ExoticSpheres8And10.hly_prop31_model_disk
